### ISSUE TITLE
Document Stable API and Add Unit Tests

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#12]
The FastAPI interface to the conversion functions appears to be converging on a stable API, with defined possible input keys (`input_url`, `input_file`, `access_token`, ...) and defined output keys (`status`, `message`, `file_data`, ...).

First, this API should be documented, possibly in a new "API Specification" document.

Second, unit tests that test the FastAPI interfaces to ensure they adhere to this API should be written. According to https://fastapi.tiangolo.com/tutorial/testing/#extended-testing-file , such tests are easily done by creating a separate python test file with a series of functions (one per test), and then running them with the pytest framework.

All the various valid (and invalid) combinations of input parameters should be individually tested to make sure the results are as expected. This will require coming up with a way to catch the authorized calls and return "true/false" (as the test requires) instead of reaching out to the real authorization server each time. I was going to say a second wiggle would be to have remote places that we can test the `input_url` functionality, but that is easy: just hit the existing test data files on github.

**Comment by tmcqueen-materials** [comment]
Well, every combination becomes possibly too large a number... I think the idea would be to start with the common cases, and expand out from there to cover as many edge cases as possible. The tests should try to avoid using real tokens (e.g. https://github.com/paradimdata/project_chameleon/blob/c3960fce375a122c61a7a99ffa85190ff3f4d3cb/tests/api_test.py#L19 ) (unless I misunderstood and that is a totally fictitious token generated to somehow make testing easier).

The Stable API documentation is nice! But I have a question -- these two:
```
endpoint_id: [REQUIRED] A string that contains the address the endpoint where chameleon is being hosted. 
opa_json: [REQUIRED] A dictionary copy of the data being passed into the POST call.
```

are not provided to any project chameleon api end point [they are generated internally by PC based on things passed to the APIs], so I don't think they are part of the API spec for PC [they are a part of the API spec for the opa auth server...).

Similarly, this one:
```
X-Auth-Access-Token: [REQUIRED] A string associated with the endpoint that will be used as a key for access.
```
Is not actually required, right? Because you can use that, or `Access-Token` (as a header), or `access_token` (as a key in the request JSON) to provide a token. And even then, the auth server might approve it even if there is no token (e.g. for public conversions)? So it, along with the other two listed here, I think (??) are optional? 

One other tiny nit: it is true all the input flavors are "OPTIONAL", but exactly *ONE* must be present... maybe there is a way to indicate that wrinkle?

Thanks!!

**Comment by tmcqueen-materials** [comment]
Regarding overriding the authorized call: according to https://docs.pytest.org/en/stable/getting-started.html#get-started , pytest runs all functions in the test file starting with `test_` or ending with `_test`. So at the top of the `api_test.py` file (after setting the TestClient, I think?), just provide an alternate definition. The simplest might be:
```
def authorized(access_token, endpoint_id, params):
    return True
```
But I suppose something slightly more refined to be able to test both success and failure to authorize cases would be better.

**Comment by pcauchy1** [comment]
The token is a bogus token so no worries there. Stable API documentation should be a bit more clear now. Let me know if there are any other adjustments you would like to see. Tests are in the works.
