### ISSUE TITLE
Enhance error message descriptions

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#16]
Verbose error messages are useful in tracking down bugs in production. While some try/except blocks return details, others do not. For those cases where it does not, it would be good to add logging that goes to the server logs to aid debugging. Specifically, a line like `traceback.print_exc()` should be added before returning HTTPExceptions. I believe these lines all need such a treatment:

https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L89
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L365
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L384
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L402
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L421
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L440
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L464
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L482
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L500
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L519
https://github.com/paradimdata/project_chameleon/blob/39195b1e3869bd13cbfdf36b6568d4364ee07c43/api.py#L565

Thank you!

**Comment by pcauchy1** [comment]
Added traceback.print_exc() to all the lines given. Also added more descriptive error messages.
