### ISSUE TITLE
Zip File TODO

### ISSUE THREAD

**Issue by pcauchy1** [paradimdata/project_chameleon#20]
# TODO: zip allows for relative path filenames, so we need to sanitize those, otherwise this might allow overwrite of arbitrary files

I read this as we just need to check if there are any other zip files that already exist with the same name and have some kind of response if there is already a file. Is that correct?

**Comment by pcauchy1** [comment]
Added validate_zip function to execute this function. I roughly followed the pseudo code. If you could double check and make sure it is working how you expected it to that would be great.

**Comment by tmcqueen-materials** [comment]
@pauchy1: It looks good to me. At some point we should come up with a set of "naughty" zipflle tests to make sure testing catches any regressions.
