### ISSUE TITLE
JSON TODO

### ISSUE THREAD

**Issue by pcauchy1** [paradimdata/project_chameleon#21]
# Maybe TODO: At this point, the output is a file of raw bytes. If output_type == "JSON", shouldwe rewrite the file as a valid JSON object? 
#This seems like a case we would never use, so I
    # tend towards "no", but then the parse_request logic should be updated to disallow output type
    # JSON when the destination is "file" or "folder".

I agree this seems like a very niche use case. I am in favor of updating the logic to disallow it. What do you think?

**Comment by tmcqueen-materials** [comment]
@pcauchy1 : agreed, lets disallow it!

**Comment by pcauchy1** [comment]
Logic has been disallowed in common_folder_handler_parse_request and common_file_handler_parse_request.
