### ISSUE TITLE
Example nit

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#28]
@pcauchy1 : While doing the PR I just did, I noticed that this file:
https://github.com/paradimdata/project_chameleon/blob/main/Instructions%20and%20Specifications/API_JS_format.md
Doesn't look right. The logo isn't showing up and the JS code as weird styling (maybe missing multiline quote makers in the markdown?)

**Comment by pcauchy1** [comment]
Just needed a tab.
