### ISSUE TITLE
"Raw" return type nits

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#4]
While creating the draft refactoring PR, I noticed that for some types, the raw return type isn't handled how I would expect.

Specifically, I would expect a "raw" return type to do two things:
1. Set the Content-Type header to application/octet-stream (for arbitrary binary data) or image/png (for a png image), etc. This allows browsers to properly handle the result based on content-type.
2. To return the raw bytes as raw bytes, not as the base64-encoded version as it currently does.

This is blocking deploying of this to make automatic downloads of on the fly converted files.

Thanks!

**Comment by pcauchy1** [comment]
I believe the 'raw' type should now have just raw bytes instead of base 64 encoded bytes. Not sure why I encoded them in the first place but they are fixed now. If you could give me an example of how you want me to set the content headers so I can make sure I get it right that would be great.

**Comment by tmcqueen-materials** [comment]
Great! You basically need to return a custom [FileResponse](https://fastapi.tiangolo.com/advanced/custom-response/#using-streamingresponse-with-file-like-objects) and specify the appropriate media type. Which media type depends on which routine -- for returning a zip response, the media type should be application/zip; for returning an image, image/png, etc. See common MIME types here: https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types

**Comment by pcauchy1** [comment]
Added streaming response with MIME types. I think I did it right but if you could double check for me that would be great.
