### ISSUE TITLE
Do not require output file name

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#6]
This line (and comparables later on) requires the caller to always provide a filename for the output file:

https://github.com/paradimdata/project_chameleon/blob/346a2344045d8f91d11113b64e82bb605d8d7c58/api.py#L92

When the output type is "file", this is reasonable. However, for output types of "raw" and "json", which are returned directly to the caller (and not put in a permanent file), this parameter should not be required (and in fact, should be ignored -- the code should use a temporary file instead if needed, just like when the input is received directly from the call, then clean it up after preparing the response).

**Comment by pcauchy1** [comment]
Currently when the output type is "raw" or "json" the "output_file" is not kept as a permanent file. 
[project_chameleon/api.py](https://github.com/paradimdata/project_chameleon/blob/fce8deea9e2ae4ebc3211b9f6082dc61337bdcc0/api.py#L421-L438)
Right now when "raw" or "json" is selected the data is extracted from the "output_file" and then the "output_file" is removed. Should I change how I handle this? If so, can you be more specific about how you would like it changed?

**Comment by tmcqueen-materials** [comment]
Basically: when the output is to a file, the value of output_file should be used as the file destination.
But for "raw" or "json" output returned to the caller, this code *should not* use output_file; instead, it should pick a temporary file name and use that instead. This avoids burden on the caller to know where a good place to write a temp file would be, and also avoids use of this as an arbitrary read or write gadget for someone trying to break in to our systems.

That help?

**Comment by pcauchy1** [comment]
Yes that makes sense. I will adjust accordingly.

**Comment by pcauchy1** [comment]
An input of 'output_file','output_folder' is not longer required. Temporary file is created instead.
