### ISSUE TITLE
Make API Stable V1

### ISSUE THREAD

**Issue by tmcqueen-materials** [paradimdata/project_chameleon#8]
As this API gets integrated into other backends, it is important for the "front end" API to have stability. What this means is, for each endpoint, to define the names and types of required and optional parameters, and then to keep the names and meaning fixed for the life of the API (until we do some major upgrade to a V2). 

For example, a hypothetical stable API contract for `rheed_convert_route` might be:

#####  `input_access_headers`: string, optional, header(s) to add for getting data from input_url. Default: [""]. Examples (depends on URL source): ["X-Auth-Access-Token: mytokenhere"] or ["Authorization: bearer;mytokenhere"].

Of course one of the three inputs must be specified. 

To clarify behavior of the outputs:

##### output_type = "JSON", output_dest = "file": writes the json {"data":"base64-bytes-of-result", "status":"ok"...} to the specified file. Returns an HTTP response to the caller with the Content-Type set appropriately to "application/json", where the json is {"status":"ok"...}

This is just an example. The details don't matter so much as deciding on a set for each endpoint and then not changing them. 

This is a blocker for deployment of project chameleon across a fleet, since we don't want changes here to break those deployments. Since this is being deployed for XRD and Laue data first, it would be great if those two conversion calls could be prioritized to get a stable API specified.

Thanks!

**Comment by pcauchy1** [comment]
Clarifying question here. Do we only want to return file with raw bytes/JSONs or do we also want the capability to return full files(like png files and txt files)? Or did you just not include those in the example here?

**Comment by tmcqueen-materials** [comment]
To be clear: "raw" doesn't mean "Bruker RAW" format. "raw" means "the raw bytes without any conversion to base64 or wrapping in json". The idea being exactly what you suggest. I make an api call (such as in https://github.com/paradimdata/project_chameleon/issues/10 ), and want the return to have the content-type and stream of bytes for the output file type (which could be text, or png, or a bunch of other things). 

The problem right now is that requesting "raw" gets you as base64 encoded output stream back, and with the wrong content-type in the return.

That help?

**Comment by pcauchy1** [comment]
Not exactly. Right now I have three different possible options for outputs after I run whatever function I choose to run. You are suggesting a new variable, output_dest, that will change what we do with these outputs. Currently there are three options:

1. Return the file that is output by the function
2. Take the file that is output by the function, convert it to raw bits(I know this is base64 encoded bits right now but that will be fixed), and return the bits.
3. Take the file that is output by the function, convert it to raw bits, put the raw bits in a JSON, return the JSON.

Your example above gives an example of roughly how output_dest will interest with the second and third output options, but not the first. My question is, how, if at all, will output_dest interact with the first option of just returning the file immediately after its processed? Or do we want to do away with that option and remove it from the code entirely? I am operating under the impression that writing raw bytes to a specified file is not the same as just returning the file immediately after it's processed.

**Comment by tmcqueen-materials** [comment]
Sorry, let me try it this way with code, and a reference to another one of the issues. Right now here is your typical output code block:
```
if 'output_type' in data:
  if data.get('output_type') == 'raw':
    with open(output_file, 'rb') as file:
      encoded_data = base64.b64encode(file.read()).decode('utf-8')
      out = encoded_data
      os.remove(output_file)
  elif data.get('output_type') == 'JSON':
    with open(output_file, 'rb') as file:
      encoded_data = base64.b64encode(file.read()).decode('utf-8')
    with open('brukerraw_out_json', 'w') as json_file:
      json.dump({"file_data": encoded_data}, json_file)
      out = json_file
    os.remove(output_file)
  else:
    out = None
else:
  out = None

if result is None:
  if out:
    return out
  else:
    return {'message': 'File converted successfully'}
else:
  raise HTTPException(status_code=500, detail=f'Failed to convert file')

```

when `output_type` is 'raw', this results in `out` being set to a byte-string corresponding to the base64-encoded characters. This then gets returned to the caller. That is not the intended behavior, since the client making the request receives a long base64 string of characters, with a content-type of "application/json". To pick the BrukerRAW file converter specifically, it really should be returning the bare output bytes (not base64 encoded), and with a content type of 'text/plain' (if returning a .txt) or 'text/csv' (if returning a .csv). Issue https://github.com/paradimdata/project_chameleon/issues/4 is about fixing that. Once https://github.com/paradimdata/project_chameleon/issues/4 is fixed, then 'raw' corresponds to the 'full file' return you describe in comment 2.

when `output_type` is 'JSON', the code above does the sensible thing: return a json with a key "file_data", whose value is the base64-encoded version of the bare output, and with a content-type of application/json.

Both of these delete the output file once it has been read back in to transmit to the caller.

when `output_type` is unspecified, the code above returns a json to the caller with the message "file converted successful", and leaves the converted file in place.

And we do in fact want all 3 of these output options! 

This issue is not about any of those things, directly. This issue is about specifying a formal API (contract, basically) for each post endpoint, and then keeping those APIs fixed from here on out (at least until a v2 arrives much later). And all that matters is that they are specified, and do what we want.

Your clarifying question is about a choice I made in my example where I don't think it matters how it is done, we just need to pick one way and go with it. Specifically, I chose in the example to separate `output_type` into two settings, `output_type` and `output_dest`. The idea being that `output_type` specifies the wire format of the output (`raw` for bare bytes, `JSON` for a JSON string with the bare bytes base64 encoded), while `output_dest` specifies whether the output goes back to the caller, or gets written to a file. 

But that is a totally arbitrary choice. You could instead choose to just keep `output_type` functioning the way you currently have it specced (`raw` = return bare bytes to the caller with the correct content type, `JSON` = return JSON back to the caller with the bare output base64 encoded, `file`/unspecified = return a JSON object with success/no success to the caller, and write the file to disk permanently). I chose differently in my example simply to highlight you have compete flexibility to change these API specifications to match what makes sense to you... but we need to pick an API for each end point and stick with it.

Hope that helps?

**Comment by pcauchy1** [comment]
OK I have added output_dest. Take a look at let me know if it looks how you expect/want it to look.
